// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticket.DAL;

#nullable disable

namespace Ticket.DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230331125517_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.Property<int>("DevelopersId")
                        .HasColumnType("int");

                    b.Property<int>("TicketsId")
                        .HasColumnType("int");

                    b.HasKey("DevelopersId", "TicketsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("DeveloperTicket");
                });

            modelBuilder.Entity("Ticket.DAL.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Automotive & Baby"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beauty & Health"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electronics"
                        });
                });

            modelBuilder.Entity("Ticket.DAL.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 2,
                            Name = "Diabetes"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Name = "Hypertension"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Name = "Asthma"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Name = "Depression"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Name = "Arthritis"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Name = "Allergy"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Name = "Flu"
                        });
                });

            modelBuilder.Entity("Ticket.DAL.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            Description = "Harum hic impedit dolore voluptate placeat.",
                            Title = "in"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Rerum totam est quo possimus sunt sunt ad.",
                            Title = "id"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Id cumque explicabo beatae.",
                            Title = "dicta"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Consectetur beatae dolorem voluptates occaecati.",
                            Title = "eius"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nulla est doloribus ut non aspernatur vero dolores.",
                            Title = "assumenda"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Et praesentium est ipsum eligendi rerum itaque voluptate quia.",
                            Title = "ex"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Optio non debitis ut molestiae dolorem ad.",
                            Title = "velit"
                        });
                });

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.HasOne("Ticket.DAL.Developer", null)
                        .WithMany()
                        .HasForeignKey("DevelopersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticket.DAL.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ticket.DAL.Developer", b =>
                {
                    b.HasOne("Ticket.DAL.Department", "Department")
                        .WithMany("Developers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Ticket.DAL.Department", b =>
                {
                    b.Navigation("Developers");
                });
#pragma warning restore 612, 618
        }
    }
}
